config/routes.rb
Rails.application.routes.draw do
  

  root 'welcome#index'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  get 'register' => 'users#new', :as => :register
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
	 mount_uploader :file, SongfileUploader
	 validates :name, presence: true 
	 validates :file, presence: true
	 validates :timestamp, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!

	validates :password, length: {minimum: 3}
	validates :password, confirmation: true
	validates :password_confirmation, presence: true

	validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login

private
	def not_authenticated
		redirect_to login_path, alert: "Please login first"
	end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	skip_before_action :require_login, only: [:index]
	def index
		@songs = Song.all
	end

	def show
		@song = Song.find(params[:id])
	end

	def new
		@song = Song.new
	end

	def edit
		@song = Song.find(params[:id])
	end

	def create 
		@song = Song.new(song_params)

		if @song.save!
			redirect_to @song
		else
			render 'new'
		end
	end

	def update
		@song = Song.find(params[:id])
		if @song.update(song_params)
			redirect_to @song
		else
			render 'edit'
		end
	end

	def destroy
		@song = Song.find(params[:id])
		@song.destroy

		redirect_to songs_path
	end


private
	def song_params
		params.require(:song).permit(:name, :timestamp, :file)
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
  	@user = User.new
  end

  def create
  	if @user = login(params[:email], params[:password])
  		redirect_back_or_to(:songs, notice: 'Login successful')
  	else
  		flash.now[:alert] = 'Login out'
      redirect_to(:login)
  	end
  end

  def destroy
  	logout
  	redirect_to(:songs)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :users, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login, only: [:index]
  def index
  	songs = Song.all
    if songs.length == 0 
      return
    end
  	songArray = Array.new
  	songs.each do |s|
  		songArray.push(s.id)
  	end

  	number = rand(songArray.length)
  	songId = songArray.at(number)
  	@song = Song.find(songId)

   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <%= yield :head %>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<header>
			<%= yield :header %>
		</header>
		<!--<div>
		    <p id="notice"><%= flash[:notice] %></p>
		    <p id="alert"><%= flash[:alert] %></p>
		  </div>-->

		<%= yield %>
		<footer class="page-footer">
			<div class="container">
				<% if current_user %>
					<%= link_to "Logout", :logout, method: :post, class: "btn" %>
				<% else %>
					<%= link_to "Login", :login, method: :get, class: "btn" %>
					<%= link_to "Register", :register, method: :get, class: "btn" %>
				<% end %>
				<%= yield :footer %>
			</div>
		</footer>
	</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
<%= yield %>
</body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
 
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@song.errors.count, "error") %> prohibited
        this song from being saved:
      </h2>
      <ul>
        <% @song.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :timestamp %><br>
    <%= f.text_field :timestamp %>
  </p>

  <p>
    <%= f.file_field :file, class: "btn" %>
  </p>
 
  <p>
    <%= f.submit class: "btn" %>
  </p>
 
<% end %>

app/views/songs/edit.html.erb
<main>
	<div class="container">
		<h1 class="center-align"> Edit song </h1>

		<%= render 'form' %>
	</div>
</main>

app/views/songs/index.html.erb
<main>
	<div class="container">
		<h1 class="center-align"> All songs</h1>
		<table class="striped">
			<thead>
				<tr>
					<th data-field="name">Name</th>
					<th data-field="timestamp">Timestamp</th>
				</tr>
			</thead>
			<tbody>
			<% @songs.each do |song| %>
				<tr>
					<td><%= song.name %></td>
					<td><%= song.timestamp %> </td>
					<td><%= link_to 'Edit', edit_song_path(song) %> </td>
					<td><%= link_to 'Delete', song_path(song),
							method: :delete,
							data: { confirm: 'Are you sure?' } %> </td>
				</tr>
			<% end %>
			</tbody>
		</table>
		<%= link_to 'New song', new_song_path, class: 'btn' %>
	</div>
</main>

app/views/songs/new.html.erb
<main>
	<div class="container">
		<h1 class="center-align"> Add new song </h1>

		<%= render 'form' %>
		
	</div>
</main>

app/views/songs/show.html.erb
<html>
<body>
<p>
  <strong>Title:</strong>
  <%= @song.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @song.name %>
</p>
</body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login", class: "btn"%>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<main>
<div class="container">
	<h1 class="center-align"> Login </h1>

	<%= render 'form' %>
	
</div>
</main>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<main>
	<div class='container'>
		<h1 class='center-align'>Editing User</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @user, class: 'btn' %> 
	</div>
</main>
<%= content_for :footer do %>
	<%= link_to 'Back', users_path, class: 'btn' %>
<% end %>

app/views/users/index.html.erb
<main>
<div class ="container">
<h1 class="center-align">Listing Users</h1>

<table class='striped'>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "btn" %>
</div>
</main>

app/views/users/new.html.erb
<main>
	<div class='container'>
			<h1 class='center-align'>New User</h1>

			<%= render 'form' %>
	</div>
</main>

app/views/users/show.html.erb
<main>
	<h1 class='center-align'>User</h1>
	<div class='container'>
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: 'btn' %> 
</div>
</main>

<%= content_for :footer do %>
	<%= link_to 'Back', users_path, class: 'btn' %>
<% end %>

app/views/welcome/index.html.erb
<% content_for :head do %>
	<title>YOU ARE AWESOME</title>
	<%= stylesheet_link_tag 'welcome' %>
<% end %>
<% if defined?(@song) %>
	<audio id="best" preload="auto">
	  <source src= "<%= @song.file.url %>">
	</audio>
	<script>
	function playSong() {
		this.currentTime = <%= @song.timestamp %>;
	    this.play();
	    best.removeEventListener('canplaythrough', playSong)
	}
	best.addEventListener('canplaythrough', playSong);
	</script>
<% end %>

<div class="flex-container">
    <div class="flex-item">YOU ARE AWESOME</div>
</div>